#!/bin/bash
# 02-generate-local-conf.sh - Generate devstack local.conf for Ironic + Neutron
#                              ML2 with sushy-tools and Cisco Nexus 9000v.
#
# Run as the stack user from /opt/stack:
#   bash 02-generate-local-conf.sh
#
# Customizable environment variables (set before running):
#
#   IRONIC_VM_COUNT        - Number of virtual bare metal nodes (default: 3)
#   IRONIC_VM_SPECS_RAM    - RAM per VM in MB (default: 3072)
#   IRONIC_VM_SPECS_DISK   - Disk per VM in GB (default: 10)
#   IRONIC_DEPLOY_DRIVER   - BMC driver: "redfish" or "ipmi" (default: redfish)
#   NETWORK_SIMULATOR      - Switch simulator type (default: cisco_nexus9k)
#                            Options: cisco_nexus9k, force10_9, force10_10,
#                                     sonic, ovs (no simulator)
#   VLAN_RANGE             - VLAN range for tenant networks (default: 100:150)
#   ADMIN_PASSWORD         - Password for all services (default: password)
#   IRONIC_REPO            - Git URL for Ironic (default: opendev.org)
#   IRONIC_BRANCH          - Git branch/ref for Ironic (default: master)
#   USE_LOCAL_IRONIC        - Set to path to use a local Ironic checkout
#   BUILD_IPA_RAMDISK      - Build IPA from source: True/False (default: False)

set -euo pipefail

# ---- Defaults ----
VM_COUNT="${IRONIC_VM_COUNT:-3}"
VM_RAM="${IRONIC_VM_SPECS_RAM:-3072}"
VM_DISK="${IRONIC_VM_SPECS_DISK:-10}"
DEPLOY_DRIVER="${IRONIC_DEPLOY_DRIVER:-redfish}"
NET_SIM="${NETWORK_SIMULATOR:-cisco_nexus9k}"
VLAN_RANGE="${VLAN_RANGE:-100:150}"
ADMIN_PASS="${ADMIN_PASSWORD:-password}"
IRONIC_REPO_URL="${IRONIC_REPO:-https://opendev.org/openstack/ironic}"
IRONIC_BRANCH="${IRONIC_BRANCH:-master}"
USE_LOCAL="${USE_LOCAL_IRONIC:-}"
BUILD_IPA="${BUILD_IPA_RAMDISK:-False}"

DEVSTACK_DIR="${DEVSTACK_DIR:-/opt/stack/devstack}"
CONF_FILE="$DEVSTACK_DIR/local.conf"

if [[ ! -d "$DEVSTACK_DIR" ]]; then
    echo "ERROR: DevStack not found at $DEVSTACK_DIR"
    echo "Clone it first: git clone https://opendev.org/openstack/devstack.git $DEVSTACK_DIR"
    exit 1
fi

echo "Generating DevStack local.conf..."
echo "  Deploy driver: $DEPLOY_DRIVER"
echo "  Network simulator: $NET_SIM"
echo "  VM count: $VM_COUNT"
echo "  VM RAM: ${VM_RAM} MB"
echo "  VM disk: ${VM_DISK} GB"
echo ""

# ---- Determine Ironic plugin source ----
if [[ -n "$USE_LOCAL" ]]; then
    IRONIC_PLUGIN="enable_plugin ironic $USE_LOCAL"
else
    IRONIC_PLUGIN="enable_plugin ironic $IRONIC_REPO_URL $IRONIC_BRANCH"
fi

# ---- Determine driver-specific settings ----
if [[ "$DEPLOY_DRIVER" == "redfish" ]]; then
    DRIVER_CONFIG=$(cat <<'DRIVEREOF'
# Use Redfish via sushy-tools emulator
IRONIC_DEPLOY_DRIVER=redfish
IRONIC_ENABLED_HARDWARE_TYPES=redfish,ipmi,fake-hardware
IRONIC_ENABLED_MANAGEMENT_INTERFACES=redfish,ipmitool,fake
IRONIC_ENABLED_POWER_INTERFACES=redfish,ipmitool,fake
IRONIC_ENABLED_BOOT_INTERFACES=redfish-virtual-media,ipxe,pxe,fake
DRIVEREOF
    )
else
    DRIVER_CONFIG=$(cat <<'DRIVEREOF'
# Use IPMI via VirtualBMC
IRONIC_DEPLOY_DRIVER=ipmi
IRONIC_ENABLED_HARDWARE_TYPES=ipmi,redfish,fake-hardware
IRONIC_ENABLED_MANAGEMENT_INTERFACES=ipmitool,redfish,fake
IRONIC_ENABLED_POWER_INTERFACES=ipmitool,redfish,fake
DRIVEREOF
    )
fi

# ---- Network simulator configuration ----
if [[ "$NET_SIM" != "ovs" ]]; then
    NET_SIM_CONFIG="IRONIC_NETWORK_SIMULATOR=$NET_SIM"
else
    NET_SIM_CONFIG="# No network switch simulator (using OVS only)"
fi

# ---- Write local.conf ----
cat > "$CONF_FILE" <<CONFEOF
[[local|localrc]]

# =============================================================================
# Ironic + Neutron ML2 DevStack Configuration
#
# This configuration sets up:
#   - Ironic with $DEPLOY_DRIVER driver and sushy-tools BMC emulator
#   - Neutron with ML2 plugin and networking-generic-switch
#   - $NET_SIM network switch simulator (for ML2 driver testing)
#   - $VM_COUNT virtual bare metal nodes
#
# Generated by: 02-generate-local-conf.sh
# =============================================================================

# ---- Ironic Plugin ----
$IRONIC_PLUGIN

# Install networking-generic-switch Neutron ML2 driver
enable_plugin networking-generic-switch https://opendev.org/openstack/networking-generic-switch

# ---- Credentials ----
ADMIN_PASSWORD=$ADMIN_PASS
DATABASE_PASSWORD=$ADMIN_PASS
RABBIT_PASSWORD=$ADMIN_PASS
SERVICE_PASSWORD=$ADMIN_PASS
SERVICE_TOKEN=$ADMIN_PASS
SWIFT_HASH=$ADMIN_PASS
SWIFT_TEMPURL_KEY=$ADMIN_PASS

# ---- Service Configuration ----
# Enable Ironic services
enable_service ironic ir-api ir-cond

# Disable nova novnc (ironic doesn't use it)
disable_service n-novnc

# Enable Swift for the direct deploy interface
enable_service s-proxy s-object s-container s-account
SWIFT_ENABLE_TEMPURLS=True

# Disable Horizon (not needed for development)
disable_service horizon

# Disable Cinder (not needed for bare metal)
disable_service cinder c-sch c-api c-vol

# Disable Tempest (run separately if needed)
disable_service tempest

# ---- Neutron Networking ----
# Disable OVN and use Neutron with OVS
disable_service ovn-controller
disable_service ovn-northd
disable_service neutron-ovn-metadata-agent

enable_service neutron-agent q-agt
enable_service neutron-dhcp q-dhcp
enable_service neutron-l3 q-l3
enable_service neutron-metadata-agent q-meta
enable_service neutron-api q-svc

Q_AGENT=openvswitch
Q_ML2_PLUGIN_MECHANISM_DRIVERS="openvswitch"
Q_USE_SECGROUP=False

# ---- ML2 VLAN Configuration for Multi-tenant Networking ----
Q_PLUGIN=ml2
ENABLE_TENANT_VLANS=True
Q_ML2_TENANT_NETWORK_TYPE=vlan
TENANT_VLAN_RANGE=$VLAN_RANGE

# ---- Ironic Networking ----
# Add link local info when registering Ironic nodes
IRONIC_USE_LINK_LOCAL=True

IRONIC_ENABLED_NETWORK_INTERFACES=flat,neutron
IRONIC_NETWORK_INTERFACE=neutron

OVS_PHYSICAL_BRIDGE=brbm
PHYSICAL_NETWORK=mynetwork
IRONIC_PROVISION_NETWORK_NAME=ironic-provision
IRONIC_PROVISION_SUBNET_PREFIX=10.0.5.0/24
IRONIC_PROVISION_SUBNET_GATEWAY=10.0.5.1

# ---- Network Switch Simulator ----
$NET_SIM_CONFIG

# ---- Ironic Driver Configuration ----
$DRIVER_CONFIG

# ---- Virtual Bare Metal Nodes ----
IRONIC_VM_COUNT=$VM_COUNT
IRONIC_BAREMETAL_BASIC_OPS=True
DEFAULT_INSTANCE_TYPE=baremetal

# VM sizing
IRONIC_VM_SPECS_RAM=$VM_RAM
IRONIC_VM_SPECS_DISK=$VM_DISK

# No ephemeral partition
IRONIC_VM_EPHEMERAL_DISK=0

# Use pre-built IPA ramdisk (faster)
IRONIC_BUILD_DEPLOY_RAMDISK=$BUILD_IPA

# Use Ironic as Nova virt driver
VIRT_DRIVER=ironic

# Set glance's default limit to be baremetal image friendly
GLANCE_LIMIT_IMAGE_SIZE_TOTAL=5000

# ---- Network Addressing ----
# Adjust if these overlap with your host network
IP_VERSION=4
NETWORK_GATEWAY=10.1.0.1
FIXED_RANGE=10.1.0.0/20
IPV4_ADDRS_SAFE_TO_USE=10.1.0.0/20

# ---- Logging ----
LOGFILE=\$HOME/devstack.log
LOGDIR=\$HOME/logs
IRONIC_VM_LOG_DIR=\$HOME/ironic-bm-logs
CONFEOF

echo "local.conf written to: $CONF_FILE"
echo ""
echo "Review the configuration, then run DevStack:"
echo "  cd $DEVSTACK_DIR"
echo "  ./stack.sh"
echo ""
if [[ "$NET_SIM" == "cisco_nexus9k" ]]; then
    echo "IMPORTANT: Ensure the Cisco Nexus 9000v QCOW2 image is at:"
    echo "  /opt/stack/nexus9300v64.10.3.7.M.qcow2"
    echo ""
    echo "The switch simulator will add ~5-10 minutes to stack.sh runtime."
fi
