#!/bin/bash
# 00-setup-controller.sh - Set up the controller node for POAP services
#
# The controller provides:
#   - DHCP server with POAP options (option 66/67) on the management network
#   - TFTP server serving switch configs and POAP script
#   - DNS for switch hostnames (optional)
#
# Run this ON the controller node.
#
# Usage:
#   sudo bash scripts/00-setup-controller.sh
#
# Prerequisites:
#   - Controller VM must be booted and accessible via floating IP
#   - Management network must be configured

set -euo pipefail

# =============================================================================
# Configuration - match terraform variables
# =============================================================================

CONTROLLER_IP="${CONTROLLER_IP:-192.168.32.254}"
MGMT_SUBNET="${MGMT_SUBNET:-192.168.32.0}"
MGMT_NETMASK="${MGMT_NETMASK:-255.255.255.0}"
MGMT_PREFIX="${MGMT_PREFIX:-24}"

# Switch management IPs
SPINE01_IP="${SPINE01_MGMT_IP:-192.168.32.11}"
SPINE02_IP="${SPINE02_MGMT_IP:-192.168.32.12}"
LEAF01_IP="${LEAF01_MGMT_IP:-192.168.32.13}"
LEAF02_IP="${LEAF02_MGMT_IP:-192.168.32.14}"

# Switch credentials
SWITCH_PASS="${SWITCH_PASSWORD:-system_s3cret!}"

# VLAN range
VLAN_START="${VLAN_START:-100}"
VLAN_END="${VLAN_END:-150}"

# BM node count
NODE_COUNT="${NODE_COUNT:-2}"

TFTP_DIR="/var/lib/tftpboot"
POAP_DIR="$(cd "$(dirname "$0")/../poap" && pwd)"
SCRIPTS_DIR="$(cd "$(dirname "$0")" && pwd)"

info() { echo "[INFO] $1"; }
pass() { echo "[PASS] $1"; }
fail() { echo "[FAIL] $1"; exit 1; }

echo "=============================================="
echo "Controller Node Setup (DHCP + TFTP for POAP)"
echo "=============================================="
echo ""

# =============================================================================
# Step 1: Install packages
# =============================================================================

info "Installing DHCP and TFTP server packages..."
apt-get update -qq
apt-get install -y -qq isc-dhcp-server tftpd-hpa sshpass >/dev/null 2>&1
pass "Packages installed"

# =============================================================================
# Step 2: Configure TFTP server
# =============================================================================

info "Configuring TFTP server..."
mkdir -p "$TFTP_DIR"

# Generate switch configs
info "Generating switch configuration files..."
export SPINE01_MGMT_IP="$SPINE01_IP"
export SPINE02_MGMT_IP="$SPINE02_IP"
export LEAF01_MGMT_IP="$LEAF01_IP"
export LEAF02_MGMT_IP="$LEAF02_IP"
export SWITCH_PASSWORD="$SWITCH_PASS"
export VLAN_START VLAN_END NODE_COUNT

bash "$POAP_DIR/generate_switch_configs.sh" "$TFTP_DIR"

# Copy POAP script
cp "$POAP_DIR/poap_script.py" "$TFTP_DIR/"
chmod 644 "$TFTP_DIR"/*

# Configure tftpd-hpa
cat > /etc/default/tftpd-hpa <<TFTPEOF
TFTP_USERNAME="tftp"
TFTP_DIRECTORY="${TFTP_DIR}"
TFTP_ADDRESS="0.0.0.0:69"
TFTP_OPTIONS="--secure --create"
TFTPEOF

systemctl restart tftpd-hpa
systemctl enable tftpd-hpa
pass "TFTP server configured at $TFTP_DIR"

# =============================================================================
# Step 3: Configure DHCP server with POAP options
# =============================================================================

info "Configuring DHCP server..."

# Detect the management interface
MGMT_IF=$(ip -o addr show | grep "$CONTROLLER_IP" | awk '{print $2}')
if [[ -z "$MGMT_IF" ]]; then
    # Try to find the first non-loopback interface
    MGMT_IF=$(ip -o link show | awk -F': ' '{print $2}' | \
        grep -v -E '^(lo|docker|veth|br-)' | head -1)
fi

info "Management interface: $MGMT_IF"

cat > /etc/dhcp/dhcpd.conf <<DHCPEOF
# DHCP configuration for POAP switch provisioning
# Generated by 00-setup-controller.sh

option domain-name "ironic.local";
default-lease-time 600;
max-lease-time 7200;
authoritative;

# POAP options
option tftp-server-name "${CONTROLLER_IP}";
option bootfile-name "poap_script.py";

subnet ${MGMT_SUBNET} netmask ${MGMT_NETMASK} {
  option routers ${CONTROLLER_IP};
  option domain-name-servers ${CONTROLLER_IP};

  # Spine01
  host spine01 {
    option host-name "spine01";
    fixed-address ${SPINE01_IP};
  }

  # Spine02
  host spine02 {
    option host-name "spine02";
    fixed-address ${SPINE02_IP};
  }

  # Leaf01
  host leaf01 {
    option host-name "leaf01";
    fixed-address ${LEAF01_IP};
  }

  # Leaf02
  host leaf02 {
    option host-name "leaf02";
    fixed-address ${LEAF02_IP};
  }
}
DHCPEOF

# Configure DHCP to listen on the management interface
cat > /etc/default/isc-dhcp-server <<DHCPDEFEOF
INTERFACESv4="${MGMT_IF}"
INTERFACESv6=""
DHCPDEFEOF

systemctl restart isc-dhcp-server
systemctl enable isc-dhcp-server
pass "DHCP server configured with POAP options"

# =============================================================================
# Step 4: DNS (optional - /etc/hosts based)
# =============================================================================

info "Adding switch hostnames to /etc/hosts..."
for entry in \
    "${SPINE01_IP} spine01" \
    "${SPINE02_IP} spine02" \
    "${LEAF01_IP} leaf01" \
    "${LEAF02_IP} leaf02"
do
    ip_addr="${entry%% *}"
    if ! grep -q "$ip_addr" /etc/hosts; then
        echo "$entry" >> /etc/hosts
    fi
done
pass "Switch hostnames added to /etc/hosts"

# =============================================================================
# Summary
# =============================================================================

echo ""
echo "=============================================="
pass "Controller setup complete!"
echo ""
echo "  TFTP directory:  $TFTP_DIR"
echo "  TFTP files:"
ls -1 "$TFTP_DIR" | sed 's/^/    /'
echo ""
echo "  DHCP server:     Listening on $MGMT_IF"
echo "  POAP options:    tftp-server=$CONTROLLER_IP, bootfile=poap_script.py"
echo ""
echo "  Switch IPs:"
echo "    spine01: $SPINE01_IP"
echo "    spine02: $SPINE02_IP"
echo "    leaf01:  $LEAF01_IP"
echo "    leaf02:  $LEAF02_IP"
echo ""
echo "  IMPORTANT: Update $TFTP_DIR/serial_to_hostname with actual"
echo "  switch serial numbers before switches boot for POAP."
echo ""
echo "  To find serial numbers after switches boot:"
echo "    openstack console log show spine01 | grep -i serial"
echo "=============================================="
