#!/bin/bash
# generate_switch_configs.sh - Generate NX-OS configuration files for all switches
#
# This script generates the startup configuration for each switch in the
# spine-leaf topology. The configs are placed in the TFTP directory on the
# controller node for POAP to download.
#
# Usage:
#   bash generate_switch_configs.sh [TFTP_DIR]
#
# The generated configs include:
#   - Management interface (mgmt0) with static IP
#   - OSPF underlay on point-to-point inter-switch links
#   - BGP EVPN (iBGP AS 65001) with route reflector setup
#   - VXLAN NVE on leaf switches
#   - VLAN-to-VNI mappings on leaf switches
#   - Access/trunk port configuration on leaf switches

set -euo pipefail

TFTP_DIR="${1:-/var/lib/tftpboot}"

# =============================================================================
# Configuration - these must match terraform variables
# =============================================================================

# Management network
MGMT_PREFIX="24"
MGMT_GATEWAY="${MGMT_GATEWAY:-192.168.32.1}"
SPINE01_MGMT="${SPINE01_MGMT_IP:-192.168.32.11}"
SPINE02_MGMT="${SPINE02_MGMT_IP:-192.168.32.12}"
LEAF01_MGMT="${LEAF01_MGMT_IP:-192.168.32.13}"
LEAF02_MGMT="${LEAF02_MGMT_IP:-192.168.32.14}"

# Switch credentials
SWITCH_PASS="${SWITCH_PASSWORD:-system_s3cret!}"

# BGP AS number (iBGP)
BGP_AS="${BGP_AS:-65001}"

# OSPF
OSPF_AREA="0.0.0.0"

# Loopback IPs for OSPF router-id and VTEP source
SPINE01_LO0="10.1.0.1"
SPINE02_LO0="10.1.0.2"
LEAF01_LO0="10.1.0.3"
LEAF02_LO0="10.1.0.4"

# VLAN/VNI range
VLAN_START="${VLAN_START:-100}"
VLAN_END="${VLAN_END:-150}"
VNI_OFFSET=10000

# BM node count (for access port config on leafs)
NODE_COUNT="${NODE_COUNT:-2}"

info() { echo "[INFO] $1"; }

mkdir -p "$TFTP_DIR"

# =============================================================================
# Spine01 Configuration
# =============================================================================

info "Generating spine01.cfg..."
cat > "$TFTP_DIR/spine01.cfg" <<SPINE01EOF
! Spine01 - Route Reflector
! Generated by generate_switch_configs.sh

hostname spine01
feature ssh
feature ospf
feature bgp
feature lldp

username admin password 0 ${SWITCH_PASS} role network-admin

interface mgmt0
  ip address ${SPINE01_MGMT}/${MGMT_PREFIX}
  no shutdown

interface loopback0
  description OSPF Router-ID / BGP Update Source
  ip address ${SPINE01_LO0}/32
  ip router ospf UNDERLAY area ${OSPF_AREA}

! Ethernet1/1 -> spine02 (spine-link)
interface Ethernet1/1
  no switchport
  ip address 10.1.1.1/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/2 -> leaf01
interface Ethernet1/2
  no switchport
  ip address 10.1.1.6/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/3 -> leaf02
interface Ethernet1/3
  no switchport
  ip address 10.1.1.14/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

router ospf UNDERLAY
  router-id ${SPINE01_LO0}

router bgp ${BGP_AS}
  router-id ${SPINE01_LO0}
  address-family l2vpn evpn
    retain route-target all
  neighbor ${SPINE02_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
  neighbor ${LEAF01_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
      route-reflector-client
  neighbor ${LEAF02_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
      route-reflector-client

copy running-config startup-config
SPINE01EOF

# =============================================================================
# Spine02 Configuration
# =============================================================================

info "Generating spine02.cfg..."
cat > "$TFTP_DIR/spine02.cfg" <<SPINE02EOF
! Spine02 - Route Reflector
! Generated by generate_switch_configs.sh

hostname spine02
feature ssh
feature ospf
feature bgp
feature lldp

username admin password 0 ${SWITCH_PASS} role network-admin

interface mgmt0
  ip address ${SPINE02_MGMT}/${MGMT_PREFIX}
  no shutdown

interface loopback0
  description OSPF Router-ID / BGP Update Source
  ip address ${SPINE02_LO0}/32
  ip router ospf UNDERLAY area ${OSPF_AREA}

! Ethernet1/1 -> spine01 (spine-link)
interface Ethernet1/1
  no switchport
  ip address 10.1.1.2/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/2 -> leaf01
interface Ethernet1/2
  no switchport
  ip address 10.1.1.10/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/3 -> leaf02
interface Ethernet1/3
  no switchport
  ip address 10.1.1.18/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

router ospf UNDERLAY
  router-id ${SPINE02_LO0}

router bgp ${BGP_AS}
  router-id ${SPINE02_LO0}
  address-family l2vpn evpn
    retain route-target all
  neighbor ${SPINE01_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
  neighbor ${LEAF01_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
      route-reflector-client
  neighbor ${LEAF02_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
      route-reflector-client

copy running-config startup-config
SPINE02EOF

# =============================================================================
# Leaf01 Configuration
# =============================================================================

info "Generating leaf01.cfg..."

# Build VLAN + VNI config
VLAN_CONFIG=""
NVE_MEMBERS=""
for vlan in $(seq "$VLAN_START" "$VLAN_END"); do
    vni=$((vlan + VNI_OFFSET))
    VLAN_CONFIG+="
vlan ${vlan}
  vn-segment ${vni}"
    NVE_MEMBERS+="
  member vni ${vni}
    ingress-replication protocol bgp"
done

# Build access port config for even-indexed BM nodes
ACCESS_PORTS=""
port_num=4  # Ethernet1/4+ (after mgmt, spine01, spine02, trunk)
for i in $(seq 0 $((NODE_COUNT - 1))); do
    if (( i % 2 == 0 )); then
        ACCESS_PORTS+="
interface Ethernet1/${port_num}
  switchport
  switchport mode access
  spanning-tree port type edge
  lldp transmit
  no shutdown"
        port_num=$((port_num + 1))
    fi
done

cat > "$TFTP_DIR/leaf01.cfg" <<LEAF01EOF
! Leaf01 - VTEP + DevStack trunk
! Generated by generate_switch_configs.sh

hostname leaf01
feature ssh
feature ospf
feature bgp
feature lldp
feature nv overlay
feature vn-segment-vlan-based

username admin password 0 ${SWITCH_PASS} role network-admin

interface mgmt0
  ip address ${LEAF01_MGMT}/${MGMT_PREFIX}
  no shutdown

interface loopback0
  description OSPF Router-ID / VTEP Source
  ip address ${LEAF01_LO0}/32
  ip router ospf UNDERLAY area ${OSPF_AREA}

! Ethernet1/1 -> spine01
interface Ethernet1/1
  no switchport
  ip address 10.1.1.5/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/2 -> spine02
interface Ethernet1/2
  no switchport
  ip address 10.1.1.9/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/3 -> DevStack (trunk - carries all tenant VLANs)
interface Ethernet1/3
  switchport
  switchport mode trunk
  switchport trunk allowed vlan ${VLAN_START}-${VLAN_END}
  spanning-tree port type edge trunk
  lldp transmit
  no shutdown

${VLAN_CONFIG}

interface nve1
  no shutdown
  source-interface loopback0
  host-reachability protocol bgp
${NVE_MEMBERS}

router ospf UNDERLAY
  router-id ${LEAF01_LO0}

router bgp ${BGP_AS}
  router-id ${LEAF01_LO0}
  address-family l2vpn evpn
  neighbor ${SPINE01_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
  neighbor ${SPINE02_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended

! Access ports for even-indexed BM nodes
${ACCESS_PORTS}

copy running-config startup-config
LEAF01EOF

# =============================================================================
# Leaf02 Configuration
# =============================================================================

info "Generating leaf02.cfg..."

# Build access port config for odd-indexed BM nodes
ACCESS_PORTS=""
port_num=3  # Ethernet1/3+ (after mgmt, spine01, spine02; no trunk on leaf02)
for i in $(seq 0 $((NODE_COUNT - 1))); do
    if (( i % 2 == 1 )); then
        ACCESS_PORTS+="
interface Ethernet1/${port_num}
  switchport
  switchport mode access
  spanning-tree port type edge
  lldp transmit
  no shutdown"
        port_num=$((port_num + 1))
    fi
done

cat > "$TFTP_DIR/leaf02.cfg" <<LEAF02EOF
! Leaf02 - VTEP (no DevStack trunk)
! Generated by generate_switch_configs.sh

hostname leaf02
feature ssh
feature ospf
feature bgp
feature lldp
feature nv overlay
feature vn-segment-vlan-based

username admin password 0 ${SWITCH_PASS} role network-admin

interface mgmt0
  ip address ${LEAF02_MGMT}/${MGMT_PREFIX}
  no shutdown

interface loopback0
  description OSPF Router-ID / VTEP Source
  ip address ${LEAF02_LO0}/32
  ip router ospf UNDERLAY area ${OSPF_AREA}

! Ethernet1/1 -> spine01
interface Ethernet1/1
  no switchport
  ip address 10.1.1.13/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

! Ethernet1/2 -> spine02
interface Ethernet1/2
  no switchport
  ip address 10.1.1.17/30
  ip ospf network point-to-point
  ip router ospf UNDERLAY area ${OSPF_AREA}
  no shutdown

${VLAN_CONFIG}

interface nve1
  no shutdown
  source-interface loopback0
  host-reachability protocol bgp
${NVE_MEMBERS}

router ospf UNDERLAY
  router-id ${LEAF02_LO0}

router bgp ${BGP_AS}
  router-id ${LEAF02_LO0}
  address-family l2vpn evpn
  neighbor ${SPINE01_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended
  neighbor ${SPINE02_LO0}
    remote-as ${BGP_AS}
    update-source loopback0
    address-family l2vpn evpn
      send-community extended

! Access ports for odd-indexed BM nodes
${ACCESS_PORTS}

copy running-config startup-config
LEAF02EOF

# =============================================================================
# Serial-to-hostname mapping file
# =============================================================================

info "Generating serial_to_hostname..."
cat > "$TFTP_DIR/serial_to_hostname" <<MAPEOF
# Serial number to hostname mapping for POAP
# Format: <serial_number> <hostname>
#
# Update these with the actual serial numbers from your Cisco 9000v images.
# You can find the serial via: openstack console log show <switch_name> | grep -i serial
#
# Example:
# 9ABCDEF1234 spine01
# 9ABCDEF5678 spine02
# 9ABCDEF9012 leaf01
# 9ABCDEF3456 leaf02
MAPEOF

info "Switch configs written to $TFTP_DIR/"
info "Files: spine01.cfg spine02.cfg leaf01.cfg leaf02.cfg serial_to_hostname"
echo ""
info "Next: Update serial_to_hostname with actual switch serial numbers"
info "Then start the TFTP/DHCP services on the controller."
